# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Download the Pipeline Scanner
      uses: wei/curl@master
      with:
          args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - name: Unzip the Pipeline Scanner
      run: unzip pipeline-scan-LATEST.zip
    - name: Create Baseline
      run: java -Dpipeline.debug=false -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --file "target/verademo.war" --json_output_file="baseline.json" || true --fail_on_severity="Very High, High" --fail_on_cwe="80"
    - name: Upload Baseline
      uses: actions/upload-artifact@v1
      with:
          name: baseline
          path: baseline.json
 
