name: Veracode SCA

 

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

 

jobs:

  VeracodeSCA:

 

    runs-on: ubuntu-latest

 

    steps:

    - uses: actions/checkout@v2

    - name: SCA Agent Scan (OSS)

      uses: ./.github/actions/sourceclear

      env:

        SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}

       

    

    - name: after

      run: echo "complete"

 

 